#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetReact.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CorporateNA")]
	public partial class TestDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGSC_WorkbookData(GSC_WorkbookData instance);
    partial void UpdateGSC_WorkbookData(GSC_WorkbookData instance);
    partial void DeleteGSC_WorkbookData(GSC_WorkbookData instance);
    partial void InsertWebUser(WebUser instance);
    partial void UpdateWebUser(WebUser instance);
    partial void DeleteWebUser(WebUser instance);
    partial void InsertGSC_Workbook(GSC_Workbook instance);
    partial void UpdateGSC_Workbook(GSC_Workbook instance);
    partial void DeleteGSC_Workbook(GSC_Workbook instance);
    #endregion
		
		public TestDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CorporateNAConnectionString3"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TestDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GSC_WorkbookData> GSC_WorkbookDatas
		{
			get
			{
				return this.GetTable<GSC_WorkbookData>();
			}
		}
		
		public System.Data.Linq.Table<WebUser> WebUsers
		{
			get
			{
				return this.GetTable<WebUser>();
			}
		}
		
		public System.Data.Linq.Table<GSC_Workbook> GSC_Workbooks
		{
			get
			{
				return this.GetTable<GSC_Workbook>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GBT.ReturnGSC")]
		public ISingleResult<ReturnGSCResult> ReturnGSC()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ReturnGSCResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GBT.uspInsertWebUser")]
		public int uspInsertWebUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="VarChar(50)")] string userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, email, password);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="GBT.GSC_WorkbookData")]
	public partial class GSC_WorkbookData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _FileName;
		
		private string _Country;
		
		private string _Service_Location;
		
		private string _Offline_Staffing_Platform;
		
		private string _Online_Bookings_Managed;
		
		private string _Supported_Languages;
		
		private string _Operational_Hours;
		
		private string _After_Hours_Access;
		
		private string _Currency;
		
		private string _GDS;
		
		private string _VIP_Number;
		
		private string _VIP_Solution;
		
		private string _Meeting_Events;
		
		private string _Group_Air_Fulfillment;
		
		private string _Incumbent;
		
		private string _FTE;
		
		private string _Offline_TSF;
		
		private string _Online_TSF;
		
		private string _ESF;
		
		private string _Air;
		
		private string _Hotel;
		
		private string _Car;
		
		private string _Virtual_Payment_Expert;
		
		private string _Current_OBT;
		
		private string _Purposed_OBT;
		
		private string _Direct_Connect_Agreement;
		
		private decimal _Current_Online_Adoption;
		
		private decimal _Target_Online_Adoption;
		
		private string _PNR_Acquire;
		
		private string _Profile_Management;
		
		private string _Standard_HR_Feed;
		
		private string _Flex_HR_Feed;
		
		private string _GSI_Overlay;
		
		private string _Mobile_Solution;
		
		private string _Expert_Auditor;
		
		private string _Premier_Insights;
		
		private string _Expert_Care;
		
		private string _Proactive_Care;
		
		private string _Data_Consolidation;
		
		private string _Single_Sign_On;
		
		private string _Connect_Portal;
		
		private string _Air_Tracks_Expert;
		
		private string _Unused_Ticket_Management;
		
		private string _Visa_Services;
		
		private string _Air__Expert;
		
		private string _Hotel_Expert;
		
		private string _PreTrip_Reporting;
		
		private string _PostTrip_Reporting;
		
		private string _Enhanced_Reporting;
		
		private string _Info_Point;
		
		private string _Travel_Alert;
		
		private string _PreTravel_Security_File;
		
		private string _TSF_Reporting;
		
		private string _International_Rate_Desk;
		
		private EntitySet<GSC_Workbook> _GSC_Workbooks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnService_LocationChanging(string value);
    partial void OnService_LocationChanged();
    partial void OnOffline_Staffing_PlatformChanging(string value);
    partial void OnOffline_Staffing_PlatformChanged();
    partial void OnOnline_Bookings_ManagedChanging(string value);
    partial void OnOnline_Bookings_ManagedChanged();
    partial void OnSupported_LanguagesChanging(string value);
    partial void OnSupported_LanguagesChanged();
    partial void OnOperational_HoursChanging(string value);
    partial void OnOperational_HoursChanged();
    partial void OnAfter_Hours_AccessChanging(string value);
    partial void OnAfter_Hours_AccessChanged();
    partial void OnCurrencyChanging(string value);
    partial void OnCurrencyChanged();
    partial void OnGDSChanging(string value);
    partial void OnGDSChanged();
    partial void OnVIP_NumberChanging(string value);
    partial void OnVIP_NumberChanged();
    partial void OnVIP_SolutionChanging(string value);
    partial void OnVIP_SolutionChanged();
    partial void OnMeeting_EventsChanging(string value);
    partial void OnMeeting_EventsChanged();
    partial void OnGroup_Air_FulfillmentChanging(string value);
    partial void OnGroup_Air_FulfillmentChanged();
    partial void OnIncumbentChanging(string value);
    partial void OnIncumbentChanged();
    partial void OnFTEChanging(string value);
    partial void OnFTEChanged();
    partial void OnOffline_TSFChanging(string value);
    partial void OnOffline_TSFChanged();
    partial void OnOnline_TSFChanging(string value);
    partial void OnOnline_TSFChanged();
    partial void OnESFChanging(string value);
    partial void OnESFChanged();
    partial void OnAirChanging(string value);
    partial void OnAirChanged();
    partial void OnHotelChanging(string value);
    partial void OnHotelChanged();
    partial void OnCarChanging(string value);
    partial void OnCarChanged();
    partial void OnVirtual_Payment_ExpertChanging(string value);
    partial void OnVirtual_Payment_ExpertChanged();
    partial void OnCurrent_OBTChanging(string value);
    partial void OnCurrent_OBTChanged();
    partial void OnPurposed_OBTChanging(string value);
    partial void OnPurposed_OBTChanged();
    partial void OnDirect_Connect_AgreementChanging(string value);
    partial void OnDirect_Connect_AgreementChanged();
    partial void OnCurrent_Online_AdoptionChanging(decimal value);
    partial void OnCurrent_Online_AdoptionChanged();
    partial void OnTarget_Online_AdoptionChanging(decimal value);
    partial void OnTarget_Online_AdoptionChanged();
    partial void OnPNR_AcquireChanging(string value);
    partial void OnPNR_AcquireChanged();
    partial void OnProfile_ManagementChanging(string value);
    partial void OnProfile_ManagementChanged();
    partial void OnStandard_HR_FeedChanging(string value);
    partial void OnStandard_HR_FeedChanged();
    partial void OnFlex_HR_FeedChanging(string value);
    partial void OnFlex_HR_FeedChanged();
    partial void OnGSI_OverlayChanging(string value);
    partial void OnGSI_OverlayChanged();
    partial void OnMobile_SolutionChanging(string value);
    partial void OnMobile_SolutionChanged();
    partial void OnExpert_AuditorChanging(string value);
    partial void OnExpert_AuditorChanged();
    partial void OnPremier_InsightsChanging(string value);
    partial void OnPremier_InsightsChanged();
    partial void OnExpert_CareChanging(string value);
    partial void OnExpert_CareChanged();
    partial void OnProactive_CareChanging(string value);
    partial void OnProactive_CareChanged();
    partial void OnData_ConsolidationChanging(string value);
    partial void OnData_ConsolidationChanged();
    partial void OnSingle_Sign_OnChanging(string value);
    partial void OnSingle_Sign_OnChanged();
    partial void OnConnect_PortalChanging(string value);
    partial void OnConnect_PortalChanged();
    partial void OnAir_Tracks_ExpertChanging(string value);
    partial void OnAir_Tracks_ExpertChanged();
    partial void OnUnused_Ticket_ManagementChanging(string value);
    partial void OnUnused_Ticket_ManagementChanged();
    partial void OnVisa_ServicesChanging(string value);
    partial void OnVisa_ServicesChanged();
    partial void OnAir__ExpertChanging(string value);
    partial void OnAir__ExpertChanged();
    partial void OnHotel_ExpertChanging(string value);
    partial void OnHotel_ExpertChanged();
    partial void OnPreTrip_ReportingChanging(string value);
    partial void OnPreTrip_ReportingChanged();
    partial void OnPostTrip_ReportingChanging(string value);
    partial void OnPostTrip_ReportingChanged();
    partial void OnEnhanced_ReportingChanging(string value);
    partial void OnEnhanced_ReportingChanged();
    partial void OnInfo_PointChanging(string value);
    partial void OnInfo_PointChanged();
    partial void OnTravel_AlertChanging(string value);
    partial void OnTravel_AlertChanged();
    partial void OnPreTravel_Security_FileChanging(string value);
    partial void OnPreTravel_Security_FileChanged();
    partial void OnTSF_ReportingChanging(string value);
    partial void OnTSF_ReportingChanged();
    partial void OnInternational_Rate_DeskChanging(string value);
    partial void OnInternational_Rate_DeskChanged();
    #endregion
		
		public GSC_WorkbookData()
		{
			this._GSC_Workbooks = new EntitySet<GSC_Workbook>(new Action<GSC_Workbook>(this.attach_GSC_Workbooks), new Action<GSC_Workbook>(this.detach_GSC_Workbooks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Service_Location", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Service_Location
		{
			get
			{
				return this._Service_Location;
			}
			set
			{
				if ((this._Service_Location != value))
				{
					this.OnService_LocationChanging(value);
					this.SendPropertyChanging();
					this._Service_Location = value;
					this.SendPropertyChanged("Service_Location");
					this.OnService_LocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Offline_Staffing_Platform", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Offline_Staffing_Platform
		{
			get
			{
				return this._Offline_Staffing_Platform;
			}
			set
			{
				if ((this._Offline_Staffing_Platform != value))
				{
					this.OnOffline_Staffing_PlatformChanging(value);
					this.SendPropertyChanging();
					this._Offline_Staffing_Platform = value;
					this.SendPropertyChanged("Offline_Staffing_Platform");
					this.OnOffline_Staffing_PlatformChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Online_Bookings_Managed", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Online_Bookings_Managed
		{
			get
			{
				return this._Online_Bookings_Managed;
			}
			set
			{
				if ((this._Online_Bookings_Managed != value))
				{
					this.OnOnline_Bookings_ManagedChanging(value);
					this.SendPropertyChanging();
					this._Online_Bookings_Managed = value;
					this.SendPropertyChanged("Online_Bookings_Managed");
					this.OnOnline_Bookings_ManagedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supported_Languages", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Supported_Languages
		{
			get
			{
				return this._Supported_Languages;
			}
			set
			{
				if ((this._Supported_Languages != value))
				{
					this.OnSupported_LanguagesChanging(value);
					this.SendPropertyChanging();
					this._Supported_Languages = value;
					this.SendPropertyChanged("Supported_Languages");
					this.OnSupported_LanguagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operational_Hours", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Operational_Hours
		{
			get
			{
				return this._Operational_Hours;
			}
			set
			{
				if ((this._Operational_Hours != value))
				{
					this.OnOperational_HoursChanging(value);
					this.SendPropertyChanging();
					this._Operational_Hours = value;
					this.SendPropertyChanged("Operational_Hours");
					this.OnOperational_HoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_After_Hours_Access", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string After_Hours_Access
		{
			get
			{
				return this._After_Hours_Access;
			}
			set
			{
				if ((this._After_Hours_Access != value))
				{
					this.OnAfter_Hours_AccessChanging(value);
					this.SendPropertyChanging();
					this._After_Hours_Access = value;
					this.SendPropertyChanged("After_Hours_Access");
					this.OnAfter_Hours_AccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				if ((this._Currency != value))
				{
					this.OnCurrencyChanging(value);
					this.SendPropertyChanging();
					this._Currency = value;
					this.SendPropertyChanged("Currency");
					this.OnCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GDS", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string GDS
		{
			get
			{
				return this._GDS;
			}
			set
			{
				if ((this._GDS != value))
				{
					this.OnGDSChanging(value);
					this.SendPropertyChanging();
					this._GDS = value;
					this.SendPropertyChanged("GDS");
					this.OnGDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIP_Number", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string VIP_Number
		{
			get
			{
				return this._VIP_Number;
			}
			set
			{
				if ((this._VIP_Number != value))
				{
					this.OnVIP_NumberChanging(value);
					this.SendPropertyChanging();
					this._VIP_Number = value;
					this.SendPropertyChanged("VIP_Number");
					this.OnVIP_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIP_Solution", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string VIP_Solution
		{
			get
			{
				return this._VIP_Solution;
			}
			set
			{
				if ((this._VIP_Solution != value))
				{
					this.OnVIP_SolutionChanging(value);
					this.SendPropertyChanging();
					this._VIP_Solution = value;
					this.SendPropertyChanged("VIP_Solution");
					this.OnVIP_SolutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meeting_Events", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Meeting_Events
		{
			get
			{
				return this._Meeting_Events;
			}
			set
			{
				if ((this._Meeting_Events != value))
				{
					this.OnMeeting_EventsChanging(value);
					this.SendPropertyChanging();
					this._Meeting_Events = value;
					this.SendPropertyChanged("Meeting_Events");
					this.OnMeeting_EventsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group_Air_Fulfillment", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Group_Air_Fulfillment
		{
			get
			{
				return this._Group_Air_Fulfillment;
			}
			set
			{
				if ((this._Group_Air_Fulfillment != value))
				{
					this.OnGroup_Air_FulfillmentChanging(value);
					this.SendPropertyChanging();
					this._Group_Air_Fulfillment = value;
					this.SendPropertyChanged("Group_Air_Fulfillment");
					this.OnGroup_Air_FulfillmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incumbent", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Incumbent
		{
			get
			{
				return this._Incumbent;
			}
			set
			{
				if ((this._Incumbent != value))
				{
					this.OnIncumbentChanging(value);
					this.SendPropertyChanging();
					this._Incumbent = value;
					this.SendPropertyChanged("Incumbent");
					this.OnIncumbentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string FTE
		{
			get
			{
				return this._FTE;
			}
			set
			{
				if ((this._FTE != value))
				{
					this.OnFTEChanging(value);
					this.SendPropertyChanging();
					this._FTE = value;
					this.SendPropertyChanged("FTE");
					this.OnFTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Offline_TSF", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Offline_TSF
		{
			get
			{
				return this._Offline_TSF;
			}
			set
			{
				if ((this._Offline_TSF != value))
				{
					this.OnOffline_TSFChanging(value);
					this.SendPropertyChanging();
					this._Offline_TSF = value;
					this.SendPropertyChanged("Offline_TSF");
					this.OnOffline_TSFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Online_TSF", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Online_TSF
		{
			get
			{
				return this._Online_TSF;
			}
			set
			{
				if ((this._Online_TSF != value))
				{
					this.OnOnline_TSFChanging(value);
					this.SendPropertyChanging();
					this._Online_TSF = value;
					this.SendPropertyChanged("Online_TSF");
					this.OnOnline_TSFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESF", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ESF
		{
			get
			{
				return this._ESF;
			}
			set
			{
				if ((this._ESF != value))
				{
					this.OnESFChanging(value);
					this.SendPropertyChanging();
					this._ESF = value;
					this.SendPropertyChanged("ESF");
					this.OnESFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Air", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Air
		{
			get
			{
				return this._Air;
			}
			set
			{
				if ((this._Air != value))
				{
					this.OnAirChanging(value);
					this.SendPropertyChanging();
					this._Air = value;
					this.SendPropertyChanged("Air");
					this.OnAirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hotel", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Hotel
		{
			get
			{
				return this._Hotel;
			}
			set
			{
				if ((this._Hotel != value))
				{
					this.OnHotelChanging(value);
					this.SendPropertyChanging();
					this._Hotel = value;
					this.SendPropertyChanged("Hotel");
					this.OnHotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Car", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Car
		{
			get
			{
				return this._Car;
			}
			set
			{
				if ((this._Car != value))
				{
					this.OnCarChanging(value);
					this.SendPropertyChanging();
					this._Car = value;
					this.SendPropertyChanged("Car");
					this.OnCarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Virtual_Payment_Expert", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Virtual_Payment_Expert
		{
			get
			{
				return this._Virtual_Payment_Expert;
			}
			set
			{
				if ((this._Virtual_Payment_Expert != value))
				{
					this.OnVirtual_Payment_ExpertChanging(value);
					this.SendPropertyChanging();
					this._Virtual_Payment_Expert = value;
					this.SendPropertyChanged("Virtual_Payment_Expert");
					this.OnVirtual_Payment_ExpertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Current_OBT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Current_OBT
		{
			get
			{
				return this._Current_OBT;
			}
			set
			{
				if ((this._Current_OBT != value))
				{
					this.OnCurrent_OBTChanging(value);
					this.SendPropertyChanging();
					this._Current_OBT = value;
					this.SendPropertyChanged("Current_OBT");
					this.OnCurrent_OBTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Purposed_OBT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Purposed_OBT
		{
			get
			{
				return this._Purposed_OBT;
			}
			set
			{
				if ((this._Purposed_OBT != value))
				{
					this.OnPurposed_OBTChanging(value);
					this.SendPropertyChanging();
					this._Purposed_OBT = value;
					this.SendPropertyChanged("Purposed_OBT");
					this.OnPurposed_OBTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direct_Connect_Agreement", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Direct_Connect_Agreement
		{
			get
			{
				return this._Direct_Connect_Agreement;
			}
			set
			{
				if ((this._Direct_Connect_Agreement != value))
				{
					this.OnDirect_Connect_AgreementChanging(value);
					this.SendPropertyChanging();
					this._Direct_Connect_Agreement = value;
					this.SendPropertyChanged("Direct_Connect_Agreement");
					this.OnDirect_Connect_AgreementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Current_Online_Adoption", DbType="Decimal(4,2) NOT NULL")]
		public decimal Current_Online_Adoption
		{
			get
			{
				return this._Current_Online_Adoption;
			}
			set
			{
				if ((this._Current_Online_Adoption != value))
				{
					this.OnCurrent_Online_AdoptionChanging(value);
					this.SendPropertyChanging();
					this._Current_Online_Adoption = value;
					this.SendPropertyChanged("Current_Online_Adoption");
					this.OnCurrent_Online_AdoptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Target_Online_Adoption", DbType="Decimal(4,2) NOT NULL")]
		public decimal Target_Online_Adoption
		{
			get
			{
				return this._Target_Online_Adoption;
			}
			set
			{
				if ((this._Target_Online_Adoption != value))
				{
					this.OnTarget_Online_AdoptionChanging(value);
					this.SendPropertyChanging();
					this._Target_Online_Adoption = value;
					this.SendPropertyChanged("Target_Online_Adoption");
					this.OnTarget_Online_AdoptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNR_Acquire", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PNR_Acquire
		{
			get
			{
				return this._PNR_Acquire;
			}
			set
			{
				if ((this._PNR_Acquire != value))
				{
					this.OnPNR_AcquireChanging(value);
					this.SendPropertyChanging();
					this._PNR_Acquire = value;
					this.SendPropertyChanged("PNR_Acquire");
					this.OnPNR_AcquireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profile_Management", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Profile_Management
		{
			get
			{
				return this._Profile_Management;
			}
			set
			{
				if ((this._Profile_Management != value))
				{
					this.OnProfile_ManagementChanging(value);
					this.SendPropertyChanging();
					this._Profile_Management = value;
					this.SendPropertyChanged("Profile_Management");
					this.OnProfile_ManagementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Standard_HR_Feed", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Standard_HR_Feed
		{
			get
			{
				return this._Standard_HR_Feed;
			}
			set
			{
				if ((this._Standard_HR_Feed != value))
				{
					this.OnStandard_HR_FeedChanging(value);
					this.SendPropertyChanging();
					this._Standard_HR_Feed = value;
					this.SendPropertyChanged("Standard_HR_Feed");
					this.OnStandard_HR_FeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flex_HR_Feed", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Flex_HR_Feed
		{
			get
			{
				return this._Flex_HR_Feed;
			}
			set
			{
				if ((this._Flex_HR_Feed != value))
				{
					this.OnFlex_HR_FeedChanging(value);
					this.SendPropertyChanging();
					this._Flex_HR_Feed = value;
					this.SendPropertyChanged("Flex_HR_Feed");
					this.OnFlex_HR_FeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSI_Overlay", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GSI_Overlay
		{
			get
			{
				return this._GSI_Overlay;
			}
			set
			{
				if ((this._GSI_Overlay != value))
				{
					this.OnGSI_OverlayChanging(value);
					this.SendPropertyChanging();
					this._GSI_Overlay = value;
					this.SendPropertyChanged("GSI_Overlay");
					this.OnGSI_OverlayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile_Solution", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Mobile_Solution
		{
			get
			{
				return this._Mobile_Solution;
			}
			set
			{
				if ((this._Mobile_Solution != value))
				{
					this.OnMobile_SolutionChanging(value);
					this.SendPropertyChanging();
					this._Mobile_Solution = value;
					this.SendPropertyChanged("Mobile_Solution");
					this.OnMobile_SolutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expert_Auditor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Expert_Auditor
		{
			get
			{
				return this._Expert_Auditor;
			}
			set
			{
				if ((this._Expert_Auditor != value))
				{
					this.OnExpert_AuditorChanging(value);
					this.SendPropertyChanging();
					this._Expert_Auditor = value;
					this.SendPropertyChanged("Expert_Auditor");
					this.OnExpert_AuditorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Premier_Insights", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Premier_Insights
		{
			get
			{
				return this._Premier_Insights;
			}
			set
			{
				if ((this._Premier_Insights != value))
				{
					this.OnPremier_InsightsChanging(value);
					this.SendPropertyChanging();
					this._Premier_Insights = value;
					this.SendPropertyChanged("Premier_Insights");
					this.OnPremier_InsightsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expert_Care", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Expert_Care
		{
			get
			{
				return this._Expert_Care;
			}
			set
			{
				if ((this._Expert_Care != value))
				{
					this.OnExpert_CareChanging(value);
					this.SendPropertyChanging();
					this._Expert_Care = value;
					this.SendPropertyChanged("Expert_Care");
					this.OnExpert_CareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proactive_Care", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Proactive_Care
		{
			get
			{
				return this._Proactive_Care;
			}
			set
			{
				if ((this._Proactive_Care != value))
				{
					this.OnProactive_CareChanging(value);
					this.SendPropertyChanging();
					this._Proactive_Care = value;
					this.SendPropertyChanged("Proactive_Care");
					this.OnProactive_CareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Consolidation", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Data_Consolidation
		{
			get
			{
				return this._Data_Consolidation;
			}
			set
			{
				if ((this._Data_Consolidation != value))
				{
					this.OnData_ConsolidationChanging(value);
					this.SendPropertyChanging();
					this._Data_Consolidation = value;
					this.SendPropertyChanged("Data_Consolidation");
					this.OnData_ConsolidationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Single_Sign_On", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Single_Sign_On
		{
			get
			{
				return this._Single_Sign_On;
			}
			set
			{
				if ((this._Single_Sign_On != value))
				{
					this.OnSingle_Sign_OnChanging(value);
					this.SendPropertyChanging();
					this._Single_Sign_On = value;
					this.SendPropertyChanged("Single_Sign_On");
					this.OnSingle_Sign_OnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Connect_Portal", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Connect_Portal
		{
			get
			{
				return this._Connect_Portal;
			}
			set
			{
				if ((this._Connect_Portal != value))
				{
					this.OnConnect_PortalChanging(value);
					this.SendPropertyChanging();
					this._Connect_Portal = value;
					this.SendPropertyChanged("Connect_Portal");
					this.OnConnect_PortalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Air_Tracks_Expert", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Air_Tracks_Expert
		{
			get
			{
				return this._Air_Tracks_Expert;
			}
			set
			{
				if ((this._Air_Tracks_Expert != value))
				{
					this.OnAir_Tracks_ExpertChanging(value);
					this.SendPropertyChanging();
					this._Air_Tracks_Expert = value;
					this.SendPropertyChanged("Air_Tracks_Expert");
					this.OnAir_Tracks_ExpertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unused_Ticket_Management", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Unused_Ticket_Management
		{
			get
			{
				return this._Unused_Ticket_Management;
			}
			set
			{
				if ((this._Unused_Ticket_Management != value))
				{
					this.OnUnused_Ticket_ManagementChanging(value);
					this.SendPropertyChanging();
					this._Unused_Ticket_Management = value;
					this.SendPropertyChanged("Unused_Ticket_Management");
					this.OnUnused_Ticket_ManagementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visa_Services", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Visa_Services
		{
			get
			{
				return this._Visa_Services;
			}
			set
			{
				if ((this._Visa_Services != value))
				{
					this.OnVisa_ServicesChanging(value);
					this.SendPropertyChanging();
					this._Visa_Services = value;
					this.SendPropertyChanged("Visa_Services");
					this.OnVisa_ServicesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Air__Expert", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Air__Expert
		{
			get
			{
				return this._Air__Expert;
			}
			set
			{
				if ((this._Air__Expert != value))
				{
					this.OnAir__ExpertChanging(value);
					this.SendPropertyChanging();
					this._Air__Expert = value;
					this.SendPropertyChanged("Air__Expert");
					this.OnAir__ExpertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hotel_Expert", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Hotel_Expert
		{
			get
			{
				return this._Hotel_Expert;
			}
			set
			{
				if ((this._Hotel_Expert != value))
				{
					this.OnHotel_ExpertChanging(value);
					this.SendPropertyChanging();
					this._Hotel_Expert = value;
					this.SendPropertyChanged("Hotel_Expert");
					this.OnHotel_ExpertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreTrip_Reporting", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PreTrip_Reporting
		{
			get
			{
				return this._PreTrip_Reporting;
			}
			set
			{
				if ((this._PreTrip_Reporting != value))
				{
					this.OnPreTrip_ReportingChanging(value);
					this.SendPropertyChanging();
					this._PreTrip_Reporting = value;
					this.SendPropertyChanged("PreTrip_Reporting");
					this.OnPreTrip_ReportingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostTrip_Reporting", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PostTrip_Reporting
		{
			get
			{
				return this._PostTrip_Reporting;
			}
			set
			{
				if ((this._PostTrip_Reporting != value))
				{
					this.OnPostTrip_ReportingChanging(value);
					this.SendPropertyChanging();
					this._PostTrip_Reporting = value;
					this.SendPropertyChanged("PostTrip_Reporting");
					this.OnPostTrip_ReportingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enhanced_Reporting", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Enhanced_Reporting
		{
			get
			{
				return this._Enhanced_Reporting;
			}
			set
			{
				if ((this._Enhanced_Reporting != value))
				{
					this.OnEnhanced_ReportingChanging(value);
					this.SendPropertyChanging();
					this._Enhanced_Reporting = value;
					this.SendPropertyChanged("Enhanced_Reporting");
					this.OnEnhanced_ReportingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Info_Point", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Info_Point
		{
			get
			{
				return this._Info_Point;
			}
			set
			{
				if ((this._Info_Point != value))
				{
					this.OnInfo_PointChanging(value);
					this.SendPropertyChanging();
					this._Info_Point = value;
					this.SendPropertyChanged("Info_Point");
					this.OnInfo_PointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Travel_Alert", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Travel_Alert
		{
			get
			{
				return this._Travel_Alert;
			}
			set
			{
				if ((this._Travel_Alert != value))
				{
					this.OnTravel_AlertChanging(value);
					this.SendPropertyChanging();
					this._Travel_Alert = value;
					this.SendPropertyChanged("Travel_Alert");
					this.OnTravel_AlertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreTravel_Security_File", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PreTravel_Security_File
		{
			get
			{
				return this._PreTravel_Security_File;
			}
			set
			{
				if ((this._PreTravel_Security_File != value))
				{
					this.OnPreTravel_Security_FileChanging(value);
					this.SendPropertyChanging();
					this._PreTravel_Security_File = value;
					this.SendPropertyChanged("PreTravel_Security_File");
					this.OnPreTravel_Security_FileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TSF_Reporting", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TSF_Reporting
		{
			get
			{
				return this._TSF_Reporting;
			}
			set
			{
				if ((this._TSF_Reporting != value))
				{
					this.OnTSF_ReportingChanging(value);
					this.SendPropertyChanging();
					this._TSF_Reporting = value;
					this.SendPropertyChanged("TSF_Reporting");
					this.OnTSF_ReportingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_International_Rate_Desk", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string International_Rate_Desk
		{
			get
			{
				return this._International_Rate_Desk;
			}
			set
			{
				if ((this._International_Rate_Desk != value))
				{
					this.OnInternational_Rate_DeskChanging(value);
					this.SendPropertyChanging();
					this._International_Rate_Desk = value;
					this.SendPropertyChanged("International_Rate_Desk");
					this.OnInternational_Rate_DeskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GSC_WorkbookData_GSC_Workbook", Storage="_GSC_Workbooks", ThisKey="FileName", OtherKey="FileName")]
		public EntitySet<GSC_Workbook> GSC_Workbooks
		{
			get
			{
				return this._GSC_Workbooks;
			}
			set
			{
				this._GSC_Workbooks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GSC_Workbooks(GSC_Workbook entity)
		{
			this.SendPropertyChanging();
			entity.GSC_WorkbookData = this;
		}
		
		private void detach_GSC_Workbooks(GSC_Workbook entity)
		{
			this.SendPropertyChanging();
			entity.GSC_WorkbookData = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="GBT.WebUsers")]
	public partial class WebUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UserID;
		
		private string _Email;
		
		private string _Password;
		
		private char _Role;
		
		private char _Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRoleChanging(char value);
    partial void OnRoleChanged();
    partial void OnActiveChanging(char value);
    partial void OnActiveChanged();
    #endregion
		
		public WebUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="Char(1) NOT NULL")]
		public char Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Char(1) NOT NULL")]
		public char Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="GBT.GSC_Workbook")]
	public partial class GSC_Workbook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FileName;
		
		private string _UploadedBy;
		
		private System.DateTime _UploadedOn;
		
		private string _ModifiedBy;
		
		private System.DateTime _ModifiedOn;
		
		private EntityRef<GSC_WorkbookData> _GSC_WorkbookData;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnUploadedByChanging(string value);
    partial void OnUploadedByChanged();
    partial void OnUploadedOnChanging(System.DateTime value);
    partial void OnUploadedOnChanged();
    partial void OnModifiedByChanging(string value);
    partial void OnModifiedByChanged();
    partial void OnModifiedOnChanging(System.DateTime value);
    partial void OnModifiedOnChanged();
    #endregion
		
		public GSC_Workbook()
		{
			this._GSC_WorkbookData = default(EntityRef<GSC_WorkbookData>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					if (this._GSC_WorkbookData.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadedBy", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UploadedBy
		{
			get
			{
				return this._UploadedBy;
			}
			set
			{
				if ((this._UploadedBy != value))
				{
					this.OnUploadedByChanging(value);
					this.SendPropertyChanging();
					this._UploadedBy = value;
					this.SendPropertyChanged("UploadedBy");
					this.OnUploadedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadedOn", DbType="DateTime NOT NULL")]
		public System.DateTime UploadedOn
		{
			get
			{
				return this._UploadedOn;
			}
			set
			{
				if ((this._UploadedOn != value))
				{
					this.OnUploadedOnChanging(value);
					this.SendPropertyChanging();
					this._UploadedOn = value;
					this.SendPropertyChanged("UploadedOn");
					this.OnUploadedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedOn", DbType="DateTime NOT NULL")]
		public System.DateTime ModifiedOn
		{
			get
			{
				return this._ModifiedOn;
			}
			set
			{
				if ((this._ModifiedOn != value))
				{
					this.OnModifiedOnChanging(value);
					this.SendPropertyChanging();
					this._ModifiedOn = value;
					this.SendPropertyChanged("ModifiedOn");
					this.OnModifiedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GSC_WorkbookData_GSC_Workbook", Storage="_GSC_WorkbookData", ThisKey="FileName", OtherKey="FileName", IsForeignKey=true)]
		public GSC_WorkbookData GSC_WorkbookData
		{
			get
			{
				return this._GSC_WorkbookData.Entity;
			}
			set
			{
				GSC_WorkbookData previousValue = this._GSC_WorkbookData.Entity;
				if (((previousValue != value) 
							|| (this._GSC_WorkbookData.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GSC_WorkbookData.Entity = null;
						previousValue.GSC_Workbooks.Remove(this);
					}
					this._GSC_WorkbookData.Entity = value;
					if ((value != null))
					{
						value.GSC_Workbooks.Add(this);
						this._FileName = value.FileName;
					}
					else
					{
						this._FileName = default(string);
					}
					this.SendPropertyChanged("GSC_WorkbookData");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class ReturnGSCResult
	{
		
		private int _ID;
		
		private string _FileName;
		
		private string _UploadedBy;
		
		private string _ModifiedBy;
		
		private string _UploadedOn;
		
		private string _ModifiedOn;
		
		public ReturnGSCResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadedBy", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UploadedBy
		{
			get
			{
				return this._UploadedBy;
			}
			set
			{
				if ((this._UploadedBy != value))
				{
					this._UploadedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this._ModifiedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadedOn", DbType="VarChar(18)")]
		public string UploadedOn
		{
			get
			{
				return this._UploadedOn;
			}
			set
			{
				if ((this._UploadedOn != value))
				{
					this._UploadedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedOn", DbType="VarChar(18)")]
		public string ModifiedOn
		{
			get
			{
				return this._ModifiedOn;
			}
			set
			{
				if ((this._ModifiedOn != value))
				{
					this._ModifiedOn = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
